baseURL = 'https://mateegt.github.io/mi-portafolio/'
languageCode = 'es-mx'
title = 'Portafolio de Fernanda Flores'
theme = 'PaperMod'

[params]
  description = "Portafolio personal y prácticas universitarias"
  author = "Fernanda Itzel Flores Valenzuela"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  
  [[menu.main]]
    name = "Prácticas"
    url = "/practicas/"
    weight = 3
  
  [[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 4